### ISSUE TITLE
FFMPEG Not working, due to broken ffmpeg package

### ISSUE THREAD

**Issue by BannerBomb** [amishshah/prism-media#19]
#### Issue:

ffmpeg not found due to node-ffmpeg-binaries links removed.
#### Further details:
- Operating System: Linux x64
- Node.js version: v10.15.3
- Commit I'm using: `9f7970f3497b12a26fb00a9d98fb3fc0a412a9ee`

**Comment by Tylertron1998** [comment]
It most definitely exists: https://www.npmjs.com/package/ffmpeg-binaries - what exactly do you mean by "links removed"?

**Comment by BannerBomb** [comment]
look at the git repo for the ffmpeg-binaries package, open the `install.js` file and under linux try to visit one of the architecture links. The files on the link have been removed. I have forked, fixed and uploaded the fixed package here `https://www.npmjs.com/package/ffmpeg-node-binaries` since it doesn't seem to be being maintained anymore.

**Comment by ShayBox** [comment]
So this is a problem with `ffmpeg-node-binaries` not `prism-media`, you should open an issue/pr on that to update the links.

That package is still "maintained", it doesn't get any commits but that's because it's so simple, and I'm guessing nobody on linux uses it to know that it broke because it's so easy to install ffmpeg correctly via your distros package manager.
Ex. `sudo apt install ffmpeg`

**Comment by amishshah** [comment]
Installing `ffmpeg-static` should work

**Comment by amishshah** [comment]
`ffmpeg-binaries` has been deprecated since https://github.com/amishshah/prism-media/commit/a8fc99d84b8d284fd628aac9f39408d84d471807 so I'll close this issue 👍
